// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MessageQueue is an autogenerated mock type for the MessageQueue type
type MessageQueue struct {
	mock.Mock
}

// PublishEvent provides a mock function with given fields: body
func (_m *MessageQueue) PublishEvent(body string) error {
	ret := _m.Called(body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
